-- 1] WAQTD EMPLOYEE NAME, SAL OF ALL THE EMPLOYEES.
select ename, sal
from emp;


-- 2] WAQTD JOB & SALARY OF ALL THE EMPLOYEES.
-- 3] WAQTD NAME & JOB OF ALL EMPLOYEES.
-- 4] WAQTD ALL THE DETAILS FROM EMP TABLE.
-- 5] WAQTD THE TABLES PRESENT IN THE DATABASE.
-- 6] WAQTD EMPLOYEE ID & DEPARTMENT NO OF ALL THE EMP'S.
-- 7] WAQTD EMP NAME & HIREDATE OF ALL EMP'S.
-- 8] WAQTD NAME & DESIGNATION OF ALL EMP'S.
-- 9] WAQTD NAME & ANNUAL SALARY OF ALL THE EMP'S.
-- 10] WAQTD NAME & HALF-TERM SALARY OF ALL THE EMP'S.
-- 11] WAQTD NAME, SALARY & SALARY WITH 25% HIKE.
-- 12] WAQTD NAME, SALARY & SALARY WITH 25% DEDUCTION.
-- 13] WAQTD NAME, SALARY & SAL WITH 12% DEDUCTION.
-- 14] WAQTD NAME, SALARY & SAL WITH 18% HIKE.
-- 15] WAQTD NAME, SALARY & SAL WITH 40% DEDUCTION.
-- 16] WAQTD NAME, SALARY & SAL WITH 7% HIKE.
-- 17] WAQTD NAME, SALARY & SAL WITH 5000 BONUS.
-- 18] WAQTD NAME, SALARY, HALF TERM SAL & 4500 BONUS IN HALF-TERM SALARY.
-- 19 WAQTD NAME, SALARY, ANNUAL SAL & 7800 BONUS IN ANNUAL SALARY.
-- 20] WAQTD NAME, ANNUAL SAL & SALARY WITH 34% HIKE.
-- 21] WAQTD NAME, SAL, HALF-TERM SALARY WITH 5% HIKE, ANNUAL SALARY WITH 23% DEDUCTION.
-- 22] WAQTD JOB, HIREDATE, DEPTNO, SAL, SAL WITH 4300 BONUS, HAL-TERM SAL WITH 3790 BONUS.
-- 23] WAQTD NAME, SAL, SAL WITH 3400 HIKE & ANUAL SAL WITH 5768 HIKE.
-- 24] WAQTD NAME, SALARY, SAL ALONG WITH 58% DEDUCTION & 4500 BONUS IN HALTERM SAL.
-- 25] WAQTD TOTAL SALARY OF ALL THE EMPLOYEES.
-- 26] WAQTD TOTAL SALARY & 3400 DEDUCTION IN HALF-TERM SAL