-- 1] WAQTD TOTAL SAL GIVEN TO EACH EMP(SAL+COMM)..



-- 2] WAQTD ALL THE DETAILS OF EMP ALONG WITH ANNUAL SAL...
-- 3] WAQTD ALL THE DETAILS OF EMP ALONG WITH ANNUAL BONUS OF 2000....
-- 4] WAQTD ALL THE DETAILS OF EMP ALONG WITH SAL HIKE OF 50RPS..
-- 5] WAQTD ALL THE DETAILS OF EMP ALONG WITH DEDUCTION OF 50 IN SAL...
-- 6] WAQTD ALL THE DETAILS ABOUT EMPLOYEE AND HIS 2 MONTHS SAL..
-- 7] WAQTD ALL THE DETAILS OF EMP ALONG WITH DEDUCTION OF 25% IN THERE ANNUAL SAL..
-- 8] WAQTD ALL THE DETAILS OF EMP ALONG WITH HIKE OF 33% IN HIS MONTHLY SAL..
-- 9] WAQTD ALL DETAILS OF EMP ALONG WITH HIKE OF 35% IN THERE ANNUAL SAL..
-- 10] WAQTD ALL DETAILS OF EMP ALONG WITH DEDUCTION OF 500 IN THERE 5 MONTHS SAL..
-- 11] WAQTD ALL DETAILS OF EMP ALONG WITH 28% OF HIKE IN THE SAL & 33% DEDUCTION IN HIS HALF TERM SAL& 45% HIKE IN HIS ANNUAL SAL...
-- 12] WAQTD ALL THE DETAILS OF EMP ALONG WITH 45% DEDUCTION IN THE SALARY FOR ALL THE EMP’S.
-- 13] WAQTD NAME, SALARY, 4 MONTHS SALARY, 32% HIKE IN THE 4 MONTHS SALARY FOR ALL THE EMP’S.
-- 14] WAQTD NAME, SALARY, 9 MONTHS SALARY, 12.34% DEDUCTION IN THE 9 MONTHS SALARY FOR ALL THE EMP’S.
-- 15] WAQTD ALL THE DETAILS ALONG WITH HALF_TERM SALARY, ANNUAL_SALARY, TOTAL SALARY FOR ALL THE EMP’S