-- 1] WAQTD DEPARTMENT NAME OF EMP WHOSE DESIGNATION IS PRESIDENT.
-- ACCOUNTING
select dname 
from dept
where deptno in (
	select deptno
	from emp
	where job = 'PRESIDENT');



-- 2] WAQTD EMPLOYEE NAME OF EMP WORKING IN ACCOUNTING DEPARTMENT.
-- CLARK
-- KING
-- MILLER
SELECT ENAME
FROM EMP
WHERE DEPTNO IN (
	SELECT DEPTNO
	FROM DEPT
	WHERE DNAME = 'ACCOUNTING');



-- 3] WAQTD EMPLOYEE NAME & SALARY OF EMP'S WHO ARE WORKING IN CHICAGO.
-- ENAME SAL
-- ---------- ----------
-- ALLEN 1600
-- WARD 1250
-- MARTIN 1250
-- BLAKE 2850
-- TURNER 1500
-- JAMES 950
-- 6 rows selected.
SELECT ENAME, SAL
FROM EMP
WHERE DEPTNO IN (
	SELECT DEPTNO
	FROM DEPT
	WHERE LOC = 'CHICAGO');



-- 4] WAQTD DETAILS OF AN EMP WHOSE WORKING IN SALES DEPARTMENT.
--  EMPNO ENAME JOB MGR HIREDATE SAL COMM DEPTNO
-- ------- ---------- --------- ---------- --------- ---------- ---------- ----------
--  7499 ALLEN SALESMAN 7698 20-FEB-81 1600 300 30
--  7521 WARD SALESMAN 7698 22-FEB-81 1250 500 30
--  7654 MARTIN SALESMAN 7698 28-SEP-81 1250 1400 30
--  7698 BLAKE MANAGER 7839 01-MAY-81 2850 30
--  7844 TURNER SALESMAN 7698 08-SEP-81 1500 0 30
--  7900 JAMES CLERK 7698 03-DEC-81 950 30
-- 6 rows selected.
SELECT *
FROM EMP
WHERE DEPTNO IN (
	SELECT DEPTNO
	FROM DEPT
	WHERE DNAME = 'SALES');



-- 5] WAQTD DETAILS OF EMP ALONG WITH ANNULAL SAL IF EMP'S ARE WORKING IN NEW YORK.
-- EMPNO ENAME JOB MGR HIREDATE SAL COMM DEPTNO SAL*12
-- ------ ---------- --------- ---------- --------- ---------- ---------- ---------- ----------
--  7782 CLARK MANAGER 7839 09-JUN-81 2450 10 29400
--  7839 KING PRESIDENT 17-NOV-81 5000 10 60000
--  7934 MILLER CLERK 7782 23-JAN-82 1300 10 15600
SELECT EMP.*, SAL*12
FROM EMP
WHERE DEPTNO IN (
	SELECT DEPTNO
	FROM DEPT
	WHERE LOC = 'NEW YORK');


-- 6] WAQTD EMPLOYEE NAME OF EMP WORKING IN OPERATIONS DEPARTMENT.
-- no rows selected
SELECT ENAME
FROM EMP
WHERE DEPTNO IN (
	SELECT DEPTNO
	FROM DEPT
	WHERE DNAME = 'OPERATIONS');



-- 7] WAQTD NAME OF EMP EARNING MORE THAN SCOTT IN ACCOUNTING DEPARTMENT.
-- KING
SELECT ENAME
FROM EMP
WHERE DEPTNO IN (
	SELECT DEPTNO
	FROM DEPT
	WHERE DNAME = 'ACCOUNTING') AND
	SAL > (SELECT SAL 
		FROM EMP
		WHERE ENAME = 'SCOTT');




-- 8] WAQTD DETAILS OF EMP WORKING AS MANAGER IN CHICAGO.
--  EMPNO ENAME JOB MGR HIREDATE SAL COMM DEPTNO
-- ---------- ---------- --------- ---------- --------- ---------- ---------- ----------
--  7698 BLAKE MANAGER 7839 01-MAY-81 2850 30
SELECT *
FROM EMP
WHERE JOB IN (
	SELECT JOB
	FROM EMP
	WHERE JOB = 'MANAGER') AND
	DEPTNO IN (
		SELECT DEPTNO
		FROM DEPT
		WHERE LOC = 'CHICAGO');



-- 9] WAQTD NAME & SALARY OF EMP'S EARNING MORE THAN KING IN ACCOUNTING DEPARTMENT.
-- NO ROWS SELECTED
SELECT ENAME, SAL
FROM EMP
WHERE SAL > (
	SELECT SAL
	FROM EMP
	WHERE ENAME = 'KING') AND
	DEPTNO IN (
		SELECT DEPTNO
		FROM DEPT
		WHERE DNAME = 'ACCOUNTING');



-- 10] WAQTD DETAILS OF EMP WHO IS WORKING AS SALESMAN IN SALES DEPARTMENT.
-- EMPNO ENAME JOB MGR HIREDATE SAL COMM DEPTNO
-- ----- ---------- --------- ---------- --------- ---------- ---------- ----------
-- 7499 ALLEN SALESMAN 7698 20-FEB-81 1600 300 30
-- 7521 WARD SALESMAN 7698 22-FEB-81 1250 500 30
-- 7654 MARTIN SALESMAN 7698 28-SEP-81 1250 1400 30
-- 7844 TURNER SALESMAN 7698 08-SEP-81 1500 0 30
SELECT *
FROM EMP
WHERE JOB = 'SALESMAN' AND
	DEPTNO IN (
		SELECT DEPTNO
		FROM DEPT
		WHERE DNAME = 'SALES');



-- 11] WAQTD NAME, SAL, JOB, HIREDATE OF EMP'S WORKING IN OPERATION DEPARTMENT & HIRED BEFORE KING.
-- NO ROWS SELECTED
SELECT ENAME, SAL, JOB, HIREDATE
FROM EMP
WHERE HIREDATE < (
	SELECT HIREDATE
	FROM EMP
	WHERE ENAME = 'KING') AND
	DEPTNO IN (
		SELECT DEPTNO
		FROM DEPT
		WHERE DNAME = 'OPERATION');



-- 12] WAQTD ALL THE EMP'S WHOSE DEPARTMENT NAME ENDING WITH 'S'.
-- ENAME
-- ----------
-- ALLEN
-- WARD
-- MARTIN
-- BLAKE
-- TURNER
-- JAMES
SELECT ENAME
FROM EMP
WHERE DEPTNO IN (
	SELECT DEPTNO
	FROM DEPT
	WHERE DNAME LIKE '%S');



-- 13] WAQTD DEPARTMENT NAME OF EMP'S WHOSE SAL IS 800.
-- DNAME
-- -----------
-- RESEARCH
SELECT DNAME
FROM DEPT
WHERE DEPTNO IN (
	SELECT DEPTNO
	FROM EMP
	WHERE SAL = 800);


-- 14] WAQTD DNAME & LOC OF EMP'S WHOSE NAME HAS CHARACTER 'A' IN IT.
-- DNAME LOC
-- -------------- -------------
-- SALES CHICAGO
-- SALES CHICAGO
-- SALES CHICAGO
-- SALES CHICAGO
-- ACCOUNTING NEW YORK
-- RESEARCH DALLAS
-- SALES CHICAGO
SELECT DNAME, LOC
FROM DEPT
WHERE DEPTNO IN (
   SELECT DEPTNO
   FROM EMP
   WHERE ENAME LIKE '%A%');
   


-- 15] WAQTD DEPT NAME OF EMP WHO EARNS COMMISSION.
-- DNAME
-- --------
-- SALES
-- SALES
-- SALES
-- SALES
SELECT DNAME
FROM DEPT
WHERE DEPTNO IN (
   SELECT DEPTNO
   FROM EMP
   WHERE COMM IS NOT NULL);



-- 16] WAQTD LOC OF EMP IF THEY EARN COMMISSION IN DEPARTMENT NUMBER 40.
-- NO ROWS SELECTED
SELECT LOC
FROM DEPT
WHERE DEPTNO IN (
	SELECT DEPTNO
	FROM EMP
	WHERE COMM > 0 AND
	DEPTNO = 40);



-- 17] WAQTD NAME OF THE EMP EARNING MAX SAL 
-- ENAME
-- ------
-- KING
SELECT ENAME
FROM EMP
WHERE SAL = (
	SELECT MAX(SAL)
	FROM EMP);